name: Preprocess Churn Data

on:
  push:
    branches:
      - main  

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          cd ./preprocessing
          python automate_jeremia-sibarani.py

      - name: Commit changes
        run: |
          cd ./preprocessing
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add clean_dataset/*.csv pipeline/*.joblib
          git commit -m "Auto-update clean dataset and pipeline [skip ci]" || echo "No changes to commit"
          git push
