name: Preprocess Churn Data

on:
  push:
    branches:
      - main

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          cd ./preprocessing
          python automate_jeremia-sibarani.py

      - name: Save output dataset to repo
        run: |
          cd ./preprocessing
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}

          git add clean_dataset/*.csv pipeline/*.joblib
          git commit -m "Save output from preprocessing pipeline"
          git push origin main
